project:
  type: book

book:
  title: Einführung in die Datenwissenschaft mit EXCEL
  author: 
  - family: Glahn
    given: Christian  
  page-navigation: true

  chapters:
  - index.md
  # - vorwort.qmd
 
  - kapitel/einleitung/kapitel.md
  
  - part: "Teil I: Datenquellen"
    chapters:
    - kapitel/dateiformate/kapitel.md
    - kapitel/daten-importieren/kapitel.md
    - kapitel/daten-organisieren/kapitel.md
    - kapitel/datentypen/kapitel.md
    - kapitel/zeichenketten/kapitel.md
    - kapitel/datenstrukturen/kapitel.md
 
  - part: "Teil II: Mathematik der Daten"
    chapters:
    - kapitel/variablen/kapitel.md
    - kapitel/neutrales-element/kapitel.md
    - kapitel/funktionen/kapitel.md
    - kapitel/boolsche-operationen/kapitel.md
    - kapitel/vektor-operationen/kapitel.md
    - kapitel/matrix-operationen/kapitel.md
  
  - part: "Teil III: Deskriptive Datenanalyse"
    chapters:
    - kapitel/daten-formen/kapitel.md
    - kapitel/daten-beschreiben/kapitel.md
    - kapitel/daten-visualisieren/kapitel.md
    - kapitel/lineare-modelle/kapitel.md

format:
  html:
    theme: bootstrap
    toc: true
    html-math-method: katex

csl: _contrib/apa.csl